"""
LEGACY / BACKUP MODULE.

This file is not used in the experiments reported in the paper.
It is kept to document alternative routing strategies explored during development.
"""

import os
import time
from typing import List
from src.reason_code.models.base import BaseModel
from src.reason_code.utils.trace import trace_span

class OpenAIModel(BaseModel):
    def __init__(self, model_name="gpt-4o"):
        self.model_name = model_name
        # 检查有没有 Key，如果没有，我们就进入"模拟模式"
        self.api_key = os.getenv("OPENAI_API_KEY")
        self.is_mock = not self.api_key 

    @trace_span(span_name="llm_generate_openai")
    def generate(self, prompt: str, n: int = 1) -> List[str]:
        if self.is_mock:
            # === 模拟模式  ===
            print(f"💰 [Mock] Pretending to call {self.model_name}...")
            time.sleep(1) # 模拟网络延迟
            # 返回一个假的修复结果，或者直接把 Prompt 稍微改改返回
            return [f"# Generated by Mock {self.model_name}\ndef solution():\n    pass"]
        
        # === 真实模式 ===
        try:
            from openai import OpenAI
            client = OpenAI(api_key=self.api_key)
            response = client.chat.completions.create(
                model=self.model_name,
                messages=[{"role": "user", "content": prompt}],
                n=n
            )
            return [c.message.content for c in response.choices]
        except Exception as e:
            print(f"OpenAI API Error: {e}")
            return []

    def name(self) -> str:
        return f"{self.model_name}{' (Mock)' if self.is_mock else ''}"